---
- name: Download Nerd Font ZIP file
  get_url:
    url: "https://github.com/ryanoasis/nerd-fonts/releases/download/v2.1.0/{{nerdfont}}.zip"
    dest: "/home/{{username}}/dotfiles/temp/{{nerdfont}}.zip"

- name: Unzip Nerd Font
  command: "unzip /home/{{username}}/dotfiles/temp/{{nerdfont}}.zip -d /usr/share/fonts/truetype/"
  become: true

- name: Update font cache
  command: fc-cache -fv
  become: true